# Branch Protection Rules for Scrabster Pro
# This file defines the branch protection rules for the repository

branches:
  main:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'build-check'
          - 'test-check'
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions:
        users: []
        teams: []
      allow_force_pushes: false
      allow_deletions: false

  develop:
    protection:
      required_status_checks:
        strict: false
        contexts:
          - 'build-check'
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      restrictions:
        users: []
        teams: []
      allow_force_pushes: true
      allow_deletions: false
