name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: |
          npm install

      - name: Install client dependencies
        run: |
          cd client && npm install

      - name: Install server dependencies
        run: |
          cd server && npm install

      - name: Build client
        run: |
          npm run client:build

      - name: Check build artifacts
        run: |
          ls -la client/dist/
          test -f client/dist/index.html

      - name: Lint CSS
        run: |
          npm run lint:css:check

  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Preview
        run: |
          echo "Deploy preview for PR #${{ github.event.number }}"
          echo "Branch: ${{ github.head_ref }}"

  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          echo "This would trigger Vercel deployment"
